# Generated by Django 4.0.6 on 2022-07-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_of_insurance', models.DateField(default=0)),
                ('end_of_technical_inspection', models.DateField(verbose_name=0)),
            ],
        ),
    ]
